# Site settings
title: AI Transcripts
description: A collection of AI conversation transcripts and notes
author: Your Name
email: your-email@example.com

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Permalink settings
permalink: /:year/:month/:day/:title/

# Collections
collections:
  transcripts:
    output: true
    permalink: /transcripts/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "AI Assistant"
  - scope:
      path: ""
      type: "transcripts"
    values:
      layout: "post"

# GitHub Pages
github:
  repo: ai-transcripts

# Optional: Google Analytics
# google_analytics: UA-XXXXXXXXX-X